#ifndef DEVICE_DATA_H_
#define DEVICE_DATA_H_

#define OPENER_DEVICE_VENDOR_ID      55512
#define OPENER_DEVICE_TYPE           7
#define OPENER_DEVICE_PRODUCT_CODE   1
#define OPENER_DEVICE_MAJOR_REVISION 1
#define OPENER_DEVICE_MINOR_REVISION 1
#define OPENER_DEVICE_NAME           "KC868-A16"
#define OPENER_DEVICE_SERIAL_NUMBER  1234567890


#endif

