/*
 * Copyright (c) 2025, Adam G. Sweeney <agsweeney@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "webui_api.h"
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

const char *webui_get_index_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Device Configuration</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           "input[type=\"checkbox\"] { width: 18px; height: 18px; margin-right: 8px; vertical-align: middle; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\" class=\"active\">Network Configuration</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>Network Configuration</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div id=\"message\" class=\"alert\" style=\"display: none;\"></div>"
           
           "<!-- Network Configuration -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Network Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"ipConfigForm\">"
           "<div class=\"form-group\">"
           "<label>"
           "<input type=\"checkbox\" id=\"use_dhcp\" onchange=\"toggleStaticFields()\">"
           "<span>Use DHCP (Automatic IP Assignment)</span>"
           "</label>"
           "</div>"
           "<div id=\"staticIpFields\" style=\"display: none;\">"
           "<div class=\"form-group\">"
           "<label for=\"ip_address\">IP Address:</label>"
           "<input type=\"text\" id=\"ip_address\" class=\"form-control\" placeholder=\"192.168.1.100\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"netmask\">Netmask:</label>"
           "<input type=\"text\" id=\"netmask\" class=\"form-control\" placeholder=\"255.255.255.0\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"gateway\">Gateway:</label>"
           "<input type=\"text\" id=\"gateway\" class=\"form-control\" placeholder=\"192.168.1.1\">"
           "</div>"
           "</div>"
           "<div id=\"dnsFields\" style=\"display: none;\">"
           "<div class=\"form-group\">"
           "<label for=\"dns1\">Primary DNS:</label>"
           "<input type=\"text\" id=\"dns1\" class=\"form-control\" placeholder=\"8.8.8.8\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"dns2\">Secondary DNS:</label>"
           "<input type=\"text\" id=\"dns2\" class=\"form-control\" placeholder=\"8.8.4.4\">"
           "</div>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveIpConfig()\">Save Network Configuration</button>"
           "</form>"
           "</div>"
           "</div>"
           
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">KC868-A16 EnIP - EtherNet/IP Controller for Kincony A16 | © 2025 Adam G. Sweeney</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "    setTimeout(function() { msg.style.display = 'none'; }, 5000);"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function loadIpConfig() {"
           "  fetch('/api/ipconfig')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const dhcpCheckbox = document.getElementById('use_dhcp');"
           "      const staticFields = document.getElementById('staticIpFields');"
           "      const dnsFields = document.getElementById('dnsFields');"
           "      if (dhcpCheckbox && data.use_dhcp !== undefined) {"
           "        dhcpCheckbox.checked = data.use_dhcp;"
           "        toggleStaticFields();"
           "      }"
           "      const ipAddr = document.getElementById('ip_address');"
           "      const netmask = document.getElementById('netmask');"
           "      const gateway = document.getElementById('gateway');"
           "      const dns1 = document.getElementById('dns1');"
           "      const dns2 = document.getElementById('dns2');"
           "      if (ipAddr) ipAddr.value = (data.ip_address && data.ip_address !== '0.0.0.0') ? data.ip_address : '';"
           "      if (netmask) netmask.value = (data.netmask && data.netmask !== '0.0.0.0') ? data.netmask : '';"
           "      if (gateway) gateway.value = (data.gateway && data.gateway !== '0.0.0.0') ? data.gateway : '';"
           "      if (dns1) dns1.value = (data.dns1 && data.dns1 !== '0.0.0.0') ? data.dns1 : '';"
           "      if (dns2) dns2.value = (data.dns2 && data.dns2 !== '0.0.0.0') ? data.dns2 : '';"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load IP configuration:', err);"
           "    });"
           "}"
           "function toggleStaticFields() {"
           "  const dhcpCheckbox = document.getElementById('use_dhcp');"
           "  const staticFields = document.getElementById('staticIpFields');"
           "  const dnsFields = document.getElementById('dnsFields');"
           "  if (dhcpCheckbox && staticFields && dnsFields) {"
           "    const useDhcp = dhcpCheckbox.checked;"
           "    staticFields.style.display = useDhcp ? 'none' : 'block';"
           "    dnsFields.style.display = useDhcp ? 'none' : 'block';"
           "  }"
           "}"
           "function saveIpConfig() {"
           "  const data = {"
           "    use_dhcp: document.getElementById('use_dhcp').checked,"
           "    ip_address: document.getElementById('ip_address').value,"
           "    netmask: document.getElementById('netmask').value,"
           "    gateway: document.getElementById('gateway').value,"
           "    dns1: document.getElementById('dns1').value,"
           "    dns2: document.getElementById('dns2').value"
           "  };"
           "  fetch('/api/ipconfig', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message, 'success');"
           "      } else {"
           "        showMessage('Failed to save IP configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save IP configuration:', err);"
           "      showMessage('Failed to save IP configuration', 'danger');"
           "    });"
           "}"
           "window.onload = function() {"
           "  loadIpConfig();"
           "};"
           "</script>"
           "</body>"
           "</html>";
}
